version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: raizes_nordeste_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: raizes_user
      POSTGRES_PASSWORD: raizes2026
      POSTGRES_DB: raizes_nordeste
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
